### ISSUE TITLE
Adding punctuation closes autocomplete list

### ISSUE THREAD

**Issue by rm-code** [atom/autocomplete-snippets#57]
![screenshot 2015-08-01 23 17 09](https://cloud.githubusercontent.com/assets/11627131/9023607/76bde190-38a3-11e5-92fd-244a7c8b408f.png)

As soon as I add a '.' the list closes. As a workaround I removed all the dots from the prefixes of my snippets, but obviously it would be nicer to have them.

**Comment by rm-code** [comment]
Closing this because there already is a related feature request here:
https://github.com/atom/autocomplete-plus/issues/293

**Comment by ezuhaib** [comment]
But https://github.com/atom/autocomplete-plus/issues/293 is not related to this issue. Its about using punctuation (e.g. period) to accept auto complete suggestions.

**Comment by rm-code** [comment]
@ezuhaib I am not sure I understand your comment, but the problem _is_ caused by autocomplete-plus as far as I know. It's autocomplete-plus which handles the keypresses in the editor and the providers (i.e. autocomplete-snippets) hook into that functionality. The problem is that autocomplete-plus doesn't "fire" when a '.' is entered by the user and therefore the actual provider is never notified.

That's how I understand the system.

**Comment by ezuhaib** [comment]
Indeed this is an issue with autocomplete-plus and not autocomplete-snippets because the former provides the prefixes to the latter, and uses regular expressions around alphanumeric characters. 

However, the issue you have referred to is about a totally different concept... it is about accepting suggestions by using punctuation.
