### ISSUE TITLE
autocomplete closes on exact match of entry

### ISSUE THREAD

**Issue by rwuttke** [atom/autocomplete-snippets#58]
Autocomplete is installed at version 2.19.0.

Issue happens on Atom 1.0.3 and 1.0.4, it works on previous versions

When using atom 1.0.2 and below, typing

**div** would show the autocomplete and stay up even when the *v* is typed.

In 1.03/4 as soon as I type the *v*, the autocomplete dialog closes.

This is happening for all sorts of entries, ie meteor-snippets

**mtp** is used to show a template template. Once I type the *p*, the autocomplete dialog closes but it does nothing.

This happens on Windows 7 and Fedora 22 (using the Fedora 21 package).

**Comment by benogle** [comment]
This was changed recently in to https://github.com/atom/autocomplete-plus/pull/547 fix https://github.com/atom/autocomplete-plus/issues/504. So when there is only one option and it is an exact match, the autocomplete box no longer shows. Snippets are a strange case because they trigger an expansion. Thinking about it....

**Comment by benogle** [comment]
This is fixed on the latest master, and should be out soon.
