### ISSUE TITLE
When prefix starts with a whitespace, the suggestion will disappear after typing first two letters

### ISSUE THREAD

**Issue by yubaoquan** [atom/autocomplete-snippets#89]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If the first letter of a snippet's prefix is whitespace, the suggestion will disappear after user typing the first two letters of prefix. If taking whitespace character as a part of snippets prefix is not recommended, it should report an error when user save the snippets file, otherwise the suggestions should show when the prefix matches one of the snippets.

### Steps to Reproduce

1. Add a snippet, be sure the first letter of the prefix is a whitespace, like this:
```
'propertyFunction':
        prefix: ' pf'
        body: '''
            ($1) {
                $2
            },
        '''
```
2. Open an empty js file in text editor, type a letter `a` and a whitespace.
3. Look at the suggestions.
4. Follow the whitespace, type the letter `p`.
5. Look at the suggestions.

**Expected behavior:** 
After typing letter `p`, the suggestion item `propertyFunction` still shows in the suggestion list.

**Actual behavior:** The suggestion item `propertyFunction` disappeared.

**Reproduces how often:** 100%

### Versions

Atom    : 1.22.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 3.6.1
git 2.13.5

OS: MacOS Sierra 10.12.6 

#### After typing a whitespace:
![image](https://user-images.githubusercontent.com/2340296/31269123-cc4741fa-aa44-11e7-8d7d-4ba96f6f4a0b.png)

#### After typing a whitespace and a letter `p`:
![image](https://user-images.githubusercontent.com/2340296/31269163-e9b914e8-aa44-11e7-8fab-f90221f3ad6a.png)

**Comment by 50Wliu** [comment]
Pretty sure it's because the prefix now becomes `pf` instead of ` pf`.

**Comment by Aerijo** [comment]
I imagine this is (sort of) intentional behaviour. Otherwise, it may as well consider the entire line to be part of the prefix (seeing as word breaks would be ignored), a change in behaviour of which could be annoying to those other packages that rely on the prefix provided by the `autocomplete-plus` package. Although the `snippets` package does allow arbitrary prefixes, I believe allowing this in `autocomplete-snippets` could lead to unexpected or desirable results.

The way the `snippets` package seems to handle it is to look at all snippets and [make the prefix regex](https://github.com/atom/snippets/blob/a51698c0dd3e64c08d289f835ebe89b67c4b1d3c/lib/snippets.coffee#L266-L274) require one or more of any observed characters to be present (so if spaces are present in a snippet definition, they will be allowed). This could probably be adpated here too, but good luck finding someone who will put in the time to do this. It seems like a lot of work to put in, especially when considering how annoying it would be to have whitespace in snippets anyway. As it is, `autocomplete-snippets` currently relies on the prefix provided by `autocomplete-plus`, [as seen here](https://github.com/atom/autocomplete-snippets/blob/ca7fe87d8d6335f156fb8491f3fbb5828993f343/lib/snippets-provider.js#L24-L28).

**Comment by yubaoquan** [comment]
Conclusion: People should avoid using whitespace as a part of snippet.
